# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Thu Aug 20 17:46:18 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design mac_system_top

create_clock -name "ACLK" -period 10.0 -waveform {0.0 5.0} [get_ports ACLK]
set_clock_transition 0.15 [get_clocks ACLK]
set_load -pin_load 0.02 [get_ports AWREADY]
set_load -pin_load 0.02 [get_ports WREADY]
set_load -pin_load 0.02 [get_ports {BRESP[1]}]
set_load -pin_load 0.02 [get_ports {BRESP[0]}]
set_load -pin_load 0.02 [get_ports BVALID]
set_load -pin_load 0.02 [get_ports ARREADY]
set_load -pin_load 0.08 [get_ports {RDATA[31]}]
set_load -pin_load 0.08 [get_ports {RDATA[30]}]
set_load -pin_load 0.08 [get_ports {RDATA[29]}]
set_load -pin_load 0.08 [get_ports {RDATA[28]}]
set_load -pin_load 0.08 [get_ports {RDATA[27]}]
set_load -pin_load 0.08 [get_ports {RDATA[26]}]
set_load -pin_load 0.08 [get_ports {RDATA[25]}]
set_load -pin_load 0.08 [get_ports {RDATA[24]}]
set_load -pin_load 0.08 [get_ports {RDATA[23]}]
set_load -pin_load 0.08 [get_ports {RDATA[22]}]
set_load -pin_load 0.08 [get_ports {RDATA[21]}]
set_load -pin_load 0.08 [get_ports {RDATA[20]}]
set_load -pin_load 0.08 [get_ports {RDATA[19]}]
set_load -pin_load 0.08 [get_ports {RDATA[18]}]
set_load -pin_load 0.08 [get_ports {RDATA[17]}]
set_load -pin_load 0.08 [get_ports {RDATA[16]}]
set_load -pin_load 0.08 [get_ports {RDATA[15]}]
set_load -pin_load 0.08 [get_ports {RDATA[14]}]
set_load -pin_load 0.08 [get_ports {RDATA[13]}]
set_load -pin_load 0.08 [get_ports {RDATA[12]}]
set_load -pin_load 0.08 [get_ports {RDATA[11]}]
set_load -pin_load 0.08 [get_ports {RDATA[10]}]
set_load -pin_load 0.08 [get_ports {RDATA[9]}]
set_load -pin_load 0.08 [get_ports {RDATA[8]}]
set_load -pin_load 0.08 [get_ports {RDATA[7]}]
set_load -pin_load 0.08 [get_ports {RDATA[6]}]
set_load -pin_load 0.08 [get_ports {RDATA[5]}]
set_load -pin_load 0.08 [get_ports {RDATA[4]}]
set_load -pin_load 0.08 [get_ports {RDATA[3]}]
set_load -pin_load 0.08 [get_ports {RDATA[2]}]
set_load -pin_load 0.08 [get_ports {RDATA[1]}]
set_load -pin_load 0.08 [get_ports {RDATA[0]}]
set_load -pin_load 0.02 [get_ports {RRESP[1]}]
set_load -pin_load 0.02 [get_ports {RRESP[0]}]
set_load -pin_load 0.02 [get_ports RVALID]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports AWVALID]
set_input_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports WVALID]
set_input_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports BREADY]
set_input_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports ARVALID]
set_input_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports RREADY]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[31]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[30]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[29]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[28]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[27]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[26]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[25]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[24]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[23]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[22]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[21]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[20]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[19]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[18]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[17]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[16]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[15]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[14]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[13]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[12]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[11]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[10]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[9]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[8]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[7]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[6]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[5]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[4]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[3]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[2]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[1]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {AWADDR[0]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[31]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[30]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[29]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[28]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[27]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[26]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[25]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[24]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[23]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[22]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[21]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[20]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[19]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[18]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[17]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[16]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[15]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[14]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[13]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[12]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[11]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[10]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[9]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[8]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[7]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[6]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[5]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[4]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[3]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[2]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[1]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WDATA[0]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WSTRB[3]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WSTRB[2]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WSTRB[1]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {WSTRB[0]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[31]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[30]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[29]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[28]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[27]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[26]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[25]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[24]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[23]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[22]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[21]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[20]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[19]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[18]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[17]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[16]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[15]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[14]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[13]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[12]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[11]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[10]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[9]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[8]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[7]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[6]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[5]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[4]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[3]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[2]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[1]}]
set_input_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {ARADDR[0]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports AWREADY]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports WREADY]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports BVALID]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports {BRESP[1]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports {BRESP[0]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports ARREADY]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports RVALID]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports {RRESP[1]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 2.5 [get_ports {RRESP[0]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[31]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[30]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[29]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[28]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[27]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[26]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[25]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[24]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[23]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[22]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[21]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[20]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[19]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[18]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[17]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[16]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[15]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[14]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[13]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[12]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[11]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[10]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[9]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[8]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[7]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[6]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[5]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[4]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[3]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[2]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[1]}]
set_output_delay -clock [get_clocks ACLK] -add_delay 4.0 [get_ports {RDATA[0]}]
set_max_fanout 20.000 [current_design]
set_max_transition 0.3 [current_design]
set_input_transition 0.15 [get_ports ACLK]
set_input_transition 0.15 [get_ports ARESETN]
set_input_transition 0.15 [get_ports {AWADDR[31]}]
set_input_transition 0.15 [get_ports {AWADDR[30]}]
set_input_transition 0.15 [get_ports {AWADDR[29]}]
set_input_transition 0.15 [get_ports {AWADDR[28]}]
set_input_transition 0.15 [get_ports {AWADDR[27]}]
set_input_transition 0.15 [get_ports {AWADDR[26]}]
set_input_transition 0.15 [get_ports {AWADDR[25]}]
set_input_transition 0.15 [get_ports {AWADDR[24]}]
set_input_transition 0.15 [get_ports {AWADDR[23]}]
set_input_transition 0.15 [get_ports {AWADDR[22]}]
set_input_transition 0.15 [get_ports {AWADDR[21]}]
set_input_transition 0.15 [get_ports {AWADDR[20]}]
set_input_transition 0.15 [get_ports {AWADDR[19]}]
set_input_transition 0.15 [get_ports {AWADDR[18]}]
set_input_transition 0.15 [get_ports {AWADDR[17]}]
set_input_transition 0.15 [get_ports {AWADDR[16]}]
set_input_transition 0.15 [get_ports {AWADDR[15]}]
set_input_transition 0.15 [get_ports {AWADDR[14]}]
set_input_transition 0.15 [get_ports {AWADDR[13]}]
set_input_transition 0.15 [get_ports {AWADDR[12]}]
set_input_transition 0.15 [get_ports {AWADDR[11]}]
set_input_transition 0.15 [get_ports {AWADDR[10]}]
set_input_transition 0.15 [get_ports {AWADDR[9]}]
set_input_transition 0.15 [get_ports {AWADDR[8]}]
set_input_transition 0.15 [get_ports {AWADDR[7]}]
set_input_transition 0.15 [get_ports {AWADDR[6]}]
set_input_transition 0.15 [get_ports {AWADDR[5]}]
set_input_transition 0.15 [get_ports {AWADDR[4]}]
set_input_transition 0.15 [get_ports {AWADDR[3]}]
set_input_transition 0.15 [get_ports {AWADDR[2]}]
set_input_transition 0.15 [get_ports {AWADDR[1]}]
set_input_transition 0.15 [get_ports {AWADDR[0]}]
set_input_transition 0.15 [get_ports AWVALID]
set_input_transition 0.15 [get_ports {WDATA[31]}]
set_input_transition 0.15 [get_ports {WDATA[30]}]
set_input_transition 0.15 [get_ports {WDATA[29]}]
set_input_transition 0.15 [get_ports {WDATA[28]}]
set_input_transition 0.15 [get_ports {WDATA[27]}]
set_input_transition 0.15 [get_ports {WDATA[26]}]
set_input_transition 0.15 [get_ports {WDATA[25]}]
set_input_transition 0.15 [get_ports {WDATA[24]}]
set_input_transition 0.15 [get_ports {WDATA[23]}]
set_input_transition 0.15 [get_ports {WDATA[22]}]
set_input_transition 0.15 [get_ports {WDATA[21]}]
set_input_transition 0.15 [get_ports {WDATA[20]}]
set_input_transition 0.15 [get_ports {WDATA[19]}]
set_input_transition 0.15 [get_ports {WDATA[18]}]
set_input_transition 0.15 [get_ports {WDATA[17]}]
set_input_transition 0.15 [get_ports {WDATA[16]}]
set_input_transition 0.15 [get_ports {WDATA[15]}]
set_input_transition 0.15 [get_ports {WDATA[14]}]
set_input_transition 0.15 [get_ports {WDATA[13]}]
set_input_transition 0.15 [get_ports {WDATA[12]}]
set_input_transition 0.15 [get_ports {WDATA[11]}]
set_input_transition 0.15 [get_ports {WDATA[10]}]
set_input_transition 0.15 [get_ports {WDATA[9]}]
set_input_transition 0.15 [get_ports {WDATA[8]}]
set_input_transition 0.15 [get_ports {WDATA[7]}]
set_input_transition 0.15 [get_ports {WDATA[6]}]
set_input_transition 0.15 [get_ports {WDATA[5]}]
set_input_transition 0.15 [get_ports {WDATA[4]}]
set_input_transition 0.15 [get_ports {WDATA[3]}]
set_input_transition 0.15 [get_ports {WDATA[2]}]
set_input_transition 0.15 [get_ports {WDATA[1]}]
set_input_transition 0.15 [get_ports {WDATA[0]}]
set_input_transition 0.15 [get_ports {WSTRB[3]}]
set_input_transition 0.15 [get_ports {WSTRB[2]}]
set_input_transition 0.15 [get_ports {WSTRB[1]}]
set_input_transition 0.15 [get_ports {WSTRB[0]}]
set_input_transition 0.15 [get_ports WVALID]
set_input_transition 0.15 [get_ports BREADY]
set_input_transition 0.15 [get_ports {ARADDR[31]}]
set_input_transition 0.15 [get_ports {ARADDR[30]}]
set_input_transition 0.15 [get_ports {ARADDR[29]}]
set_input_transition 0.15 [get_ports {ARADDR[28]}]
set_input_transition 0.15 [get_ports {ARADDR[27]}]
set_input_transition 0.15 [get_ports {ARADDR[26]}]
set_input_transition 0.15 [get_ports {ARADDR[25]}]
set_input_transition 0.15 [get_ports {ARADDR[24]}]
set_input_transition 0.15 [get_ports {ARADDR[23]}]
set_input_transition 0.15 [get_ports {ARADDR[22]}]
set_input_transition 0.15 [get_ports {ARADDR[21]}]
set_input_transition 0.15 [get_ports {ARADDR[20]}]
set_input_transition 0.15 [get_ports {ARADDR[19]}]
set_input_transition 0.15 [get_ports {ARADDR[18]}]
set_input_transition 0.15 [get_ports {ARADDR[17]}]
set_input_transition 0.15 [get_ports {ARADDR[16]}]
set_input_transition 0.15 [get_ports {ARADDR[15]}]
set_input_transition 0.15 [get_ports {ARADDR[14]}]
set_input_transition 0.15 [get_ports {ARADDR[13]}]
set_input_transition 0.15 [get_ports {ARADDR[12]}]
set_input_transition 0.15 [get_ports {ARADDR[11]}]
set_input_transition 0.15 [get_ports {ARADDR[10]}]
set_input_transition 0.15 [get_ports {ARADDR[9]}]
set_input_transition 0.15 [get_ports {ARADDR[8]}]
set_input_transition 0.15 [get_ports {ARADDR[7]}]
set_input_transition 0.15 [get_ports {ARADDR[6]}]
set_input_transition 0.15 [get_ports {ARADDR[5]}]
set_input_transition 0.15 [get_ports {ARADDR[4]}]
set_input_transition 0.15 [get_ports {ARADDR[3]}]
set_input_transition 0.15 [get_ports {ARADDR[2]}]
set_input_transition 0.15 [get_ports {ARADDR[1]}]
set_input_transition 0.15 [get_ports {ARADDR[0]}]
set_input_transition 0.15 [get_ports ARVALID]
set_input_transition 0.15 [get_ports RREADY]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.3 [get_clocks ACLK]
set_clock_uncertainty -hold 0.3 [get_clocks ACLK]
